use std::error::Error;
use std::fmt;
use std::fs;
use std::os::windows::fs::MetadataExt;
use std::path::{Path, PathBuf};

use windows_sys::Win32::Storage::FileSystem::FILE_ATTRIBUTE_REPARSE_POINT;

const GENERATED_MARKER: &str = "Generated by Swaw Kit Proj.";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DevelopmentEnvironmentRepair {
    NoPublication,
    Current,
    RemovedStale,
}

pub(crate) fn repair_development_environment(
    data_root: &Path,
) -> Result<DevelopmentEnvironmentRepair, DevelopmentEnvironmentRepairError> {
    let environment_root = data_root.join("dev_env");
    validate_managed_path(&environment_root, "managed development environment root", true)?;

    let publications = [
        Publication {
            path: environment_root.join("env.cmd"),
            kind: PublicationKind::Cmd,
        },
        Publication {
            path: environment_root.join("env.ps1"),
            kind: PublicationKind::PowerShell,
        },
    ];
    let state_path = environment_root.join("_state.json");
    for path in publications
        .iter()
        .map(|publication| publication.path.as_path())
        .chain(std::iter::once(state_path.as_path()))
    {
        validate_managed_path(path, "managed development environment publication path", false)?;
    }

    let existing: Vec<_> = publications
        .iter()
        .filter(|publication| publication.path.is_file())
        .collect();
    if existing.is_empty() {
        if state_path.is_file() {
            fs::remove_file(&state_path)
                .map_err(|error| repair_error("remove", &state_path, error))?;
        }
        return Ok(DevelopmentEnvironmentRepair::NoPublication);
    }

    let expected_root = std::path::absolute(&environment_root).map_err(|error| {
        DevelopmentEnvironmentRepairError::new(format!(
            "invalid development environment root '{}': {error}",
            environment_root.display()
        ))
    })?;
    let mut all_current = true;
    for publication in &existing {
        let declared = read_declared_root(publication)?;
        all_current &= declared.as_deref().is_some_and(|path| {
            std::path::absolute(path)
                .ok()
                .is_some_and(|path| path_eq(&path, &expected_root))
        });
    }
    if all_current {
        return Ok(DevelopmentEnvironmentRepair::Current);
    }

    for path in publications
        .iter()
        .map(|publication| publication.path.as_path())
        .chain(std::iter::once(state_path.as_path()))
    {
        if path.is_file() {
            fs::remove_file(path).map_err(|error| repair_error("remove", path, error))?;
        }
    }
    Ok(DevelopmentEnvironmentRepair::RemovedStale)
}

struct Publication {
    path: PathBuf,
    kind: PublicationKind,
}

#[derive(Clone, Copy)]
enum PublicationKind {
    Cmd,
    PowerShell,
}

fn read_declared_root(
    publication: &Publication,
) -> Result<Option<PathBuf>, DevelopmentEnvironmentRepairError> {
    let content = fs::read_to_string(&publication.path)
        .map_err(|error| repair_error("read", &publication.path, error))?;
    if !content.contains(GENERATED_MARKER) {
        return Err(DevelopmentEnvironmentRepairError::new(format!(
            concat!(
                "a development environment file is not recognized as generated content: {}. ",
                "Manual repair is required."
            ),
            publication.path.display()
        )));
    }
    let values: Vec<_> = content
        .lines()
        .filter_map(|line| parse_declared_root(line, publication.kind))
        .collect();
    if values.len() != 1 {
        return Ok(None);
    }
    Ok(Some(PathBuf::from(&values[0])))
}

fn parse_declared_root(line: &str, kind: PublicationKind) -> Option<String> {
    let line = line.trim_end();
    let (prefix, suffix) = match kind {
        PublicationKind::Cmd => (r#"set "SWAWKIT_DEV_ENV_ROOT="#, '"'),
        PublicationKind::PowerShell => ("$env:SWAWKIT_DEV_ENV_ROOT = '", '\''),
    };
    let start = line.get(..prefix.len())?;
    if !start.eq_ignore_ascii_case(prefix) || !line.ends_with(suffix) {
        return None;
    }
    let value = &line[prefix.len()..line.len() - suffix.len_utf8()];
    Some(match kind {
        PublicationKind::Cmd => value.replace("%%", "%"),
        PublicationKind::PowerShell => value.replace("''", "'"),
    })
}

fn validate_managed_path(
    path: &Path,
    label: &str,
    must_be_directory: bool,
) -> Result<(), DevelopmentEnvironmentRepairError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(repair_error("inspect", path, error)),
    };
    if metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
        return Err(DevelopmentEnvironmentRepairError::new(format!(
            "the {label} cannot be a reparse point: {}",
            path.display()
        )));
    }
    if must_be_directory && !metadata.is_dir() {
        return Err(DevelopmentEnvironmentRepairError::new(format!(
            "the {label} must be a directory: {}",
            path.display()
        )));
    }
    Ok(())
}

fn path_eq(left: &Path, right: &Path) -> bool {
    left.as_os_str()
        .to_string_lossy()
        .eq_ignore_ascii_case(&right.as_os_str().to_string_lossy())
}

fn repair_error(
    action: &str,
    path: &Path,
    error: std::io::Error,
) -> DevelopmentEnvironmentRepairError {
    DevelopmentEnvironmentRepairError::new(format!(
        "cannot {action} development environment publication '{}': {error}",
        path.display()
    ))
}

#[derive(Debug)]
pub(crate) struct DevelopmentEnvironmentRepairError {
    message: String,
}

impl DevelopmentEnvironmentRepairError {
    fn new(message: String) -> Self {
        Self { message }
    }
}

impl fmt::Display for DevelopmentEnvironmentRepairError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl Error for DevelopmentEnvironmentRepairError {}

#[cfg(test)]
mod tests;
