[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0

$ProjRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
. (Join-Path $ProjRoot '_core\engine.ps1')

function Assert-ProjCoreEnvironmentTest {
    param(
        [Parameter(Mandatory = $true)][bool]$Condition,
        [Parameter(Mandatory = $true)][string]$Message
    )
    if (-not $Condition) {
        throw "Assertion failed: $Message"
    }
}

function ConvertTo-ProjCoreEnvironmentLiteral {
    param([Parameter(Mandatory = $true)][string]$Value)
    return "'$($Value.Replace("'", "''"))'"
}

function Publish-ProjCoreEnvironmentFixture {
    param(
        [Parameter(Mandatory = $true)][string]$EnvironmentRoot,
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string]$Marker
    )

    $Placeholder = Get-ProjDevelopmentEnvironmentGenerationPlaceholder
    $Cmd = @(
        '@echo off'
        'rem Generated by Swaw Kit Proj. Re-run ".dev.setup"; do not edit.'
        "set `"SWAWKIT_PROJ_DEV_GENERATION_ID=$Placeholder`""
        "set `"SWAWKIT_PROJ_DEV_ENV_ROOT=$EnvironmentRoot`""
    ) -join "`r`n"
    $Cmd += "`r`n"
    $Ps1 = @(
        '# Generated by Swaw Kit Proj. Re-run ".dev.setup"; do not edit.'
        "`$env:SWAWKIT_PROJ_DEV_GENERATION_ID = '$Placeholder'"
        "`$env:SWAWKIT_PROJ_DEV_ENV_SCHEMA = 'swawkit.proj-dev.environment.v0'"
        (
            "`$env:SWAWKIT_PROJ_DEV_PROJECT_ROOT = " +
            (ConvertTo-ProjCoreEnvironmentLiteral -Value $ProjectRoot)
        )
        (
            "`$env:SWAWKIT_PROJ_DEV_ENV_ROOT = " +
            (ConvertTo-ProjCoreEnvironmentLiteral -Value $EnvironmentRoot)
        )
        "`$env:SWAWKIT_PROJ_TEST_CORE_ENV_MARKER = '$Marker'"
        (
            '$env:SWAWKIT_PROJ_TEST_CORE_ENV_LOAD_COUNT = ' +
            '([int]$env:SWAWKIT_PROJ_TEST_CORE_ENV_LOAD_COUNT + 1).ToString()'
        )
    ) -join "`r`n"
    $Ps1 += "`r`n"
    $GenerationId = Get-ProjDevelopmentEnvironmentContentGenerationId `
        -CmdContent $Cmd `
        -Ps1Content $Ps1
    $Cmd = $Cmd.Replace($Placeholder, $GenerationId)
    $Ps1 = $Ps1.Replace($Placeholder, $GenerationId)
    [IO.File]::WriteAllText((Join-Path $EnvironmentRoot 'env.cmd'), $Cmd)
    [IO.File]::WriteAllText((Join-Path $EnvironmentRoot 'env.ps1'), $Ps1)
    $State = New-ProjDevelopmentEnvironmentState `
        -GenerationId $GenerationId `
        -Declarations (Get-ProjDevelopmentDeclarationSnapshot)
    [IO.File]::WriteAllText(
        (Get-ProjDevelopmentEnvironmentStatePath `
            -EnvironmentRoot $EnvironmentRoot),
        (($State | ConvertTo-Json -Depth 10) + "`r`n"),
        [Text.UTF8Encoding]::new($false)
    )
    return $GenerationId
}

$TestTemporaryBase = [IO.Path]::GetFullPath(
    (Join-Path $ProjRoot '..\..\data\_test')
)
[void][IO.Directory]::CreateDirectory($TestTemporaryBase)
$TemporaryRoot = Join-Path $TestTemporaryBase (
    "swawkit-proj-core-environment-$([Guid]::NewGuid().ToString('N'))"
)
$ControlHome = [IO.Path]::GetFullPath((Join-Path $ProjRoot '..\..'))
$EntryName = "test-core-env-$([Guid]::NewGuid().ToString('N'))"
$ProjectRoot = Join-Path $TemporaryRoot 'project'
$EntryRoot = Join-Path $TemporaryRoot 'entries'
$ActionRoot = Join-Path $ProjectRoot '.swaw'
$CommandRoot = Join-Path $ActionRoot 'probe'
$ManagedCommandRoot = Join-Path $ActionRoot 'managed-probe'
$DataRoot = Join-Path $ControlHome "data\proj.$EntryName"
$EnvironmentRoot = Join-Path $DataRoot 'dev_env'
$EntryPath = Join-Path $EntryRoot "$EntryName.cmd"
$CapturePath = Join-Path $TemporaryRoot 'capture.txt'

$OwnedVariables = @(
    'SWAWKIT_PROJ_PROTOCOL',
    'SWAWKIT_PROJ_TARGET_PROJECT_ROOT',
    'SWAWKIT_PROJ_ACTION_ROOT',
    'SWAWKIT_PROJ_DATA_ROOT',
    'SWAWKIT_PROJ_ENTRY_COMMAND',
    'SWAWKIT_PROJ_ENTRY_FILE',
    'SWAWKIT_PROJ_BUN_MODE',
    'SWAWKIT_PROJ_BUN_VERSION',
    'SWAWKIT_PROJ_BUN_SHA256',
    'SWAWKIT_PROJ_TEST_CORE_ENV_CAPTURE',
    'SWAWKIT_PROJ_TEST_CORE_ENV_MARKER',
    'SWAWKIT_PROJ_TEST_CORE_ENV_LOAD_COUNT'
)
$SavedEnvironment = @{}
foreach ($Name in $OwnedVariables) {
    $SavedEnvironment[$Name] = [Environment]::GetEnvironmentVariable(
        $Name,
        [EnvironmentVariableTarget]::Process
    )
}
$SavedDevelopmentEnvironment = @{}
$ProcessEnvironment = [Environment]::GetEnvironmentVariables(
    [EnvironmentVariableTarget]::Process
)
foreach ($Name in [string[]]@($ProcessEnvironment.Keys)) {
    if ($Name.StartsWith(
        'SWAWKIT_PROJ_DEV_',
        [StringComparison]::OrdinalIgnoreCase
    )) {
        $SavedDevelopmentEnvironment[$Name] = [string]$ProcessEnvironment[$Name]
        [Environment]::SetEnvironmentVariable($Name, $null, 'Process')
    }
}

try {
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DEV_EMPTY_TEST_VALUE',
        '',
        [EnvironmentVariableTarget]::Process
    )
    Assert-ProjCoreEnvironmentTest `
        -Condition (-not (Test-ProjDevelopmentEnvironmentActive)) `
        -Message 'an empty development variable was treated as an active environment'

    [void][IO.Directory]::CreateDirectory($CommandRoot)
    [void][IO.Directory]::CreateDirectory($ManagedCommandRoot)
    [void][IO.Directory]::CreateDirectory($EntryRoot)
    [IO.File]::WriteAllText($EntryPath, '@exit /b 0')
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    [void](Resolve-ProjProjectDataRoot `
        -ProjHome $ControlHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $EntryPath)
    [void][IO.Directory]::CreateDirectory($EnvironmentRoot)
    [IO.File]::WriteAllText(
        (Join-Path $CommandRoot 'run.ps1'),
        @'
$ErrorActionPreference = 'Stop'
[IO.File]::WriteAllText(
    $env:SWAWKIT_PROJ_TEST_CORE_ENV_CAPTURE,
    "$env:SWAWKIT_PROJ_TEST_CORE_ENV_MARKER|$env:SWAWKIT_PROJ_ENTRY_COMMAND"
)
$global:LASTEXITCODE = 0
'@
    )
    [IO.File]::WriteAllText(
        (Join-Path $ManagedCommandRoot 'run.ps1'),
        @'
$ErrorActionPreference = 'Stop'
$KernelRoot = Join-Path $env:SWAWKIT_HOME '_lib\proj'
. (Join-Path $KernelRoot '_core\engine.ps1')
$Context = Get-ProjProjectContext -ProjHome $env:SWAWKIT_HOME
[void](Import-ProjDevelopmentEnvironment -ProjectContext $Context)
[IO.File]::WriteAllText(
    $env:SWAWKIT_PROJ_TEST_CORE_ENV_CAPTURE,
    "$env:SWAWKIT_PROJ_TEST_CORE_ENV_MARKER|$env:SWAWKIT_PROJ_ENTRY_COMMAND"
)
$global:LASTEXITCODE = 0
'@
    )

    $env:SWAWKIT_PROJ_PROTOCOL = '1'
    $env:SWAWKIT_PROJ_TARGET_PROJECT_ROOT = $ProjectRoot
    $env:SWAWKIT_PROJ_ACTION_ROOT = $ActionRoot
    $env:SWAWKIT_PROJ_DATA_ROOT = $DataRoot
    $env:SWAWKIT_PROJ_ENTRY_COMMAND = 'spoofed-entry-name'
    $env:SWAWKIT_PROJ_ENTRY_FILE = $EntryPath
    $env:SWAWKIT_PROJ_TEST_CORE_ENV_CAPTURE = $CapturePath
    $env:SWAWKIT_PROJ_TEST_CORE_ENV_MARKER = 'ambient'

    $ProjectContext = Get-ProjProjectContext -ProjHome $ControlHome
    Assert-ProjCoreEnvironmentTest `
        -Condition ([string]$ProjectContext.EntryName -ceq $EntryName) `
        -Message 'the entry name was not derived from the real entry file'
    Assert-ProjCoreEnvironmentTest `
        -Condition (-not ([IO.Path]::GetDirectoryName(
            [string]$ProjectContext.EntryFile
        )).Equals(
            [string]$ProjectContext.ProjectRoot,
            [StringComparison]::OrdinalIgnoreCase
        )) `
        -Message 'the fixture did not exercise an entry outside the project root'

    $ExitCode = Invoke-ProjMain -KernelRoot $ProjRoot -Arguments @('probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ExitCode -eq 0 -and
            [IO.File]::ReadAllText($CapturePath) -ceq "ambient|$EntryName") `
        -Message 'a project without a managed environment lost the ambient PATH contract'
    Assert-ProjCoreEnvironmentTest `
        -Condition ([string]$env:SWAWKIT_PROJ_ENTRY_COMMAND -ceq
            'spoofed-entry-name') `
        -Message 'the Core did not restore the caller environment after execution'

    $env:SWAWKIT_PROJ_BUN_MODE = ' MANAGED '
    $env:SWAWKIT_PROJ_BUN_VERSION = 'Latest'
    $env:SWAWKIT_PROJ_BUN_SHA256 = 'SHA256:ABCDEF'
    $NormalizedDeclarations = Get-ProjDevelopmentDeclarationSnapshot
    Assert-ProjCoreEnvironmentTest `
        -Condition (
            [string]$NormalizedDeclarations['SWAWKIT_PROJ_BUN_MODE'] -ceq
                'managed' -and
            [string]$NormalizedDeclarations['SWAWKIT_PROJ_BUN_VERSION'] -ceq
                'Latest' -and
            [string]$NormalizedDeclarations['SWAWKIT_PROJ_BUN_SHA256'] -ceq
                'abcdef'
        ) `
        -Message 'declaration normalization overrode module-owned version semantics'
    $env:SWAWKIT_PROJ_BUN_MODE = 'managed'
    $env:SWAWKIT_PROJ_BUN_VERSION = '9.9.9'
    $env:SWAWKIT_PROJ_BUN_SHA256 = ''
    $MissingPlainExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($MissingPlainExitCode -eq 0 -and
            [IO.File]::ReadAllText($CapturePath) -ceq
                "ambient|$EntryName") `
        -Message 'a missing managed environment blocked an ambient command'
    $MissingManagedExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('managed-probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($MissingManagedExitCode -eq 1) `
        -Message 'a managed command accepted an unpublished environment'
    foreach ($Name in @(
        'SWAWKIT_PROJ_BUN_MODE',
        'SWAWKIT_PROJ_BUN_VERSION',
        'SWAWKIT_PROJ_BUN_SHA256'
    )) {
        [Environment]::SetEnvironmentVariable($Name, $null, 'Process')
    }

    $GenerationId = Publish-ProjCoreEnvironmentFixture `
        -EnvironmentRoot $EnvironmentRoot `
        -ProjectRoot $ProjectRoot `
        -Marker managed

    $ValidPs1 = [IO.File]::ReadAllText((Join-Path $EnvironmentRoot 'env.ps1'))
    [IO.File]::AppendAllText(
        (Join-Path $EnvironmentRoot 'env.ps1'),
        "`$env:SWAWKIT_PROJ_TEST_CORE_ENV_MARKER = 'tampered'`r`n"
    )
    $TamperedExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('managed-probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($TamperedExitCode -eq 1) `
        -Message 'modified environment script content retained a valid generation'
    [IO.File]::WriteAllText(
        (Join-Path $EnvironmentRoot 'env.ps1'),
        $ValidPs1
    )

    $ExitCode = Invoke-ProjMain -KernelRoot $ProjRoot -Arguments @('probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ExitCode -eq 0 -and
            [IO.File]::ReadAllText($CapturePath) -ceq
                "ambient|$EntryName") `
        -Message 'the Core injected a published environment into an ambient command'
    $ManagedExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('managed-probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ManagedExitCode -eq 0 -and
            [IO.File]::ReadAllText($CapturePath) -ceq
                "managed|$EntryName") `
        -Message 'a managed command did not activate the published environment'

    $env:SWAWKIT_PROJ_BUN_MODE = 'managed'
    $env:SWAWKIT_PROJ_BUN_VERSION = '9.9.9'
    $env:SWAWKIT_PROJ_BUN_SHA256 = ''
    $ChangedPlainExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ChangedPlainExitCode -eq 0 -and
            [IO.File]::ReadAllText($CapturePath) -ceq
                "ambient|$EntryName") `
        -Message 'a changed declaration blocked an environment-agnostic command'
    $ChangedManagedExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('managed-probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ChangedManagedExitCode -eq 1) `
        -Message 'a managed command accepted a changed declaration'
    $ControlExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('.info')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($ControlExitCode -eq 0) `
        -Message 'a changed declaration blocked an environment-agnostic command'
    foreach ($Name in @(
        'SWAWKIT_PROJ_BUN_MODE',
        'SWAWKIT_PROJ_BUN_VERSION',
        'SWAWKIT_PROJ_BUN_SHA256'
    )) {
        [Environment]::SetEnvironmentVariable($Name, $null, 'Process')
    }

    $env:SWAWKIT_PROJ_DEV_ENV_SCHEMA = 'swawkit.proj-dev.environment.v0'
    $env:SWAWKIT_PROJ_DEV_PROJECT_ROOT = $ProjectRoot
    $env:SWAWKIT_PROJ_DEV_ENV_ROOT = $EnvironmentRoot
    $env:SWAWKIT_PROJ_DEV_GENERATION_ID = $GenerationId
    $NewGenerationId = Publish-ProjCoreEnvironmentFixture `
        -EnvironmentRoot $EnvironmentRoot `
        -ProjectRoot $ProjectRoot `
        -Marker managed-v2
    $StaleActiveExitCode = Invoke-ProjMain `
        -KernelRoot $ProjRoot `
        -Arguments @('probe')
    Assert-ProjCoreEnvironmentTest `
        -Condition ($NewGenerationId -cne $GenerationId -and
            $StaleActiveExitCode -eq 1) `
        -Message 'the global guard accepted an older active environment generation'
    $env:SWAWKIT_PROJ_DEV_GENERATION_ID = $NewGenerationId

    $env:SWAWKIT_PROJ_DEV_PROJECT_ROOT = Join-Path $TemporaryRoot 'foreign-project'
    $env:SWAWKIT_PROJ_DEV_ENV_ROOT = Join-Path $TemporaryRoot (
        'foreign-project\data\dev_env'
    )
    foreach ($Address in @('probe')) {
        $RejectedForeignEnvironment = $false
        try {
            $ForeignExitCode = Invoke-ProjMain `
                -KernelRoot $ProjRoot `
                -Arguments @($Address)
            $RejectedForeignEnvironment = $ForeignExitCode -eq 1
        } catch {
            $RejectedForeignEnvironment =
                $_.Exception.Message -like (
                    "*Another project's development environment*"
                )
        }
        Assert-ProjCoreEnvironmentTest `
            -Condition $RejectedForeignEnvironment `
            -Message (
                "the Core did not reject a foreign environment before $Address"
            )
    }
} finally {
    if ([IO.Directory]::Exists($DataRoot) -and
        [IO.Path]::GetFileName($DataRoot) -ceq "proj.$EntryName") {
        Remove-Item -LiteralPath $DataRoot -Recurse -Force
    }
    if ([IO.Directory]::Exists($TemporaryRoot)) {
        [IO.Directory]::Delete($TemporaryRoot, $true)
    }
    $CurrentEnvironment = [Environment]::GetEnvironmentVariables(
        [EnvironmentVariableTarget]::Process
    )
    foreach ($Name in [string[]]@($CurrentEnvironment.Keys)) {
        if ($Name.StartsWith(
            'SWAWKIT_PROJ_DEV_',
            [StringComparison]::OrdinalIgnoreCase
        )) {
            [Environment]::SetEnvironmentVariable($Name, $null, 'Process')
        }
    }
    foreach ($Name in $SavedDevelopmentEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable(
            $Name,
            [string]$SavedDevelopmentEnvironment[$Name],
            'Process'
        )
    }
    foreach ($Name in $OwnedVariables) {
        [Environment]::SetEnvironmentVariable(
            $Name,
            $SavedEnvironment[$Name],
            'Process'
        )
    }
}

Write-Host '[PASS] Proj Core development environment activation' `
    -ForegroundColor Green
$global:LASTEXITCODE = 0
