[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0

$ProjRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
. (Join-Path $ProjRoot '_core\engine.ps1')

function Assert-ProjDataRootTest {
    param(
        [Parameter(Mandatory = $true)][bool]$Condition,
        [Parameter(Mandatory = $true)][string]$Message
    )
    if (-not $Condition) {
        throw "Assertion failed: $Message"
    }
}

$TestBase = [IO.Path]::GetFullPath(
    (Join-Path $ProjRoot '..\..\data\_test')
)
[void][IO.Directory]::CreateDirectory($TestBase)
$TemporaryRoot = Join-Path $TestBase (
    "swawkit-proj-data-root-$([Guid]::NewGuid().ToString('N'))"
)
$ProjHome = Join-Path $TemporaryRoot 'swaw-kit-home'
$ProjectRoot = Join-Path $TemporaryRoot 'project'
$DataDirectory = Join-Path $ProjHome 'data'
$ActionRoot = Join-Path $ProjectRoot '.swaw'
$PreviousDataRoot = [Environment]::GetEnvironmentVariable(
    'SWAWKIT_PROJ_DATA_ROOT',
    [EnvironmentVariableTarget]::Process
)

try {
    [void][IO.Directory]::CreateDirectory($ProjHome)
    [void][IO.Directory]::CreateDirectory($ProjectRoot)
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )

    $AlphaEntry = Join-Path $ProjectRoot 'alpha.cmd'
    [IO.File]::WriteAllText($AlphaEntry, '@echo off')
    $AlphaRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $AlphaEntry
    Assert-ProjDataRootTest `
        -Condition ($AlphaRoot -ceq (
            Join-Path $ProjHome 'data\proj.alpha'
        ) -and
            [IO.File]::Exists((Join-Path $AlphaRoot '_entry.json'))) `
        -Message 'a fresh entry did not create data/proj.<entry-name>'

    $DirectPlan = Get-ProjDataRootPlan `
        -DataDirectory $DataDirectory `
        -EntryFile $AlphaEntry `
        -InheritedDataRoot $AlphaRoot
    Assert-ProjDataRootTest `
        -Condition ($DirectPlan.Kind -ceq 'Direct') `
        -Message 'matching entry name and File ID did not resolve directly'

    $LegacyEntry = Join-Path $ProjectRoot 'legacy.cmd'
    [IO.File]::WriteAllText($LegacyEntry, '@echo legacy')
    $LegacyRoot = Join-Path $ProjectRoot 'data\proj.legacy'
    [void][IO.Directory]::CreateDirectory($LegacyRoot)
    $LegacyIdentity = Get-ProjEntryFileIdentity -EntryFile $LegacyEntry
    Write-ProjEntryIdentityRecord `
        -DataRoot $LegacyRoot `
        -EntryName 'legacy' `
        -EntryFile $LegacyEntry `
        -Identity $LegacyIdentity
    $LegacyEnvironmentRoot = Join-Path $LegacyRoot 'dev_env'
    [void][IO.Directory]::CreateDirectory($LegacyEnvironmentRoot)
    [IO.File]::WriteAllText(
        (Join-Path $LegacyEnvironmentRoot 'env.cmd'),
        "rem Generated by Swaw Kit Proj.`r`nset X=$LegacyRoot`r`n"
    )
    [IO.File]::WriteAllText(
        (Join-Path $LegacyEnvironmentRoot 'env.ps1'),
        "# Generated by Swaw Kit Proj.`r`n`$env:X = '$LegacyRoot'`r`n"
    )
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    $MigratedRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $LegacyEntry
    Assert-ProjDataRootTest `
        -Condition ($MigratedRoot -ceq (
            Join-Path $ProjHome 'data\proj.legacy'
        ) -and
            [IO.Directory]::Exists($MigratedRoot) -and
            -not [IO.Directory]::Exists($LegacyRoot) -and
            -not [IO.Directory]::Exists((Join-Path $ProjectRoot 'data')) -and
            -not [IO.File]::Exists((Join-Path $MigratedRoot 'dev_env\env.cmd')) -and
            -not [IO.File]::Exists((Join-Path $MigratedRoot 'dev_env\env.ps1'))) `
        -Message 'legacy DataRoot migration did not invalidate generated paths'

    $LegacyRenamedEntry = Join-Path $ProjectRoot 'legacy-renamed.cmd'
    [IO.File]::WriteAllText($LegacyRenamedEntry, '@echo renamed')
    $LegacyOldRoot = Join-Path $ProjectRoot 'data\proj.legacy-old'
    [void][IO.Directory]::CreateDirectory($LegacyOldRoot)
    Write-ProjEntryIdentityRecord `
        -DataRoot $LegacyOldRoot `
        -EntryName 'legacy-old' `
        -EntryFile $LegacyRenamedEntry `
        -Identity (Get-ProjEntryFileIdentity -EntryFile $LegacyRenamedEntry)
    $env:SWAWKIT_PROJ_DATA_ROOT = $null
    $LegacyRenameClaim = [pscustomobject]@{ Approved = $false }
    $MigratedRenamedRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $LegacyRenamedEntry `
        -ClaimApprover {
            param($Claim)
            $LegacyRenameClaim.Approved =
                $Claim.Kind -ceq 'ClaimMigrateLegacy' -and
                $Claim.SourceDataRoot -ceq $LegacyOldRoot
            return $LegacyRenameClaim.Approved
        }
    Assert-ProjDataRootTest `
        -Condition ($LegacyRenameClaim.Approved -and
            $MigratedRenamedRoot -ceq (
                Join-Path $ProjHome 'data\proj.legacy-renamed'
            ) -and
            -not [IO.Directory]::Exists($LegacyOldRoot)) `
        -Message 'a renamed legacy DataRoot bypassed claim or was not migrated'

    $BetaEntry = Join-Path $ProjectRoot 'beta.cmd'
    [IO.File]::Move($AlphaEntry, $BetaEntry)
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    $Claims = [pscustomobject]@{
        Rename = $false
        Context = $false
        Current = $false
        MissingRecord = $false
    }
    $BetaRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $BetaEntry `
        -ClaimApprover {
            param($Claim)
            $Claims.Rename =
                $Claim.Kind -ceq 'ClaimRename' -and
                $Claim.SourceDataRoot -ceq $AlphaRoot
            $Claims.Context =
                $Claim.ProjectRoot -ceq $ProjectRoot -and
                $Claim.ActionRoot -ceq $ActionRoot -and
                -not [string]::IsNullOrWhiteSpace($Claim.VolumeId) -and
                -not [string]::IsNullOrWhiteSpace($Claim.FileId)
            return $Claims.Rename -and $Claims.Context
        }
    Assert-ProjDataRootTest `
        -Condition ($Claims.Rename -and $Claims.Context -and
            $BetaRoot -ceq (Join-Path $ProjHome 'data\proj.beta') -and
            -not [IO.Directory]::Exists($AlphaRoot)) `
        -Message 'rename claim omitted context or did not complete'

    $GammaEntry = Join-Path $ProjectRoot 'gamma.cmd'
    [IO.File]::Copy($BetaEntry, $GammaEntry)
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    $GammaRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $GammaEntry
    Assert-ProjDataRootTest `
        -Condition ($GammaRoot -ceq (
            Join-Path $ProjHome 'data\proj.gamma'
        )) `
        -Message 'a copied entry did not receive a new DataRoot'

    $Replacement = Join-Path $ProjectRoot 'replacement.cmd'
    $Backup = Join-Path $ProjectRoot 'gamma.backup.cmd'
    [IO.File]::WriteAllText($Replacement, '@echo replaced')
    [IO.File]::Replace($Replacement, $GammaEntry, $Backup, $true)
    [IO.File]::Delete($Backup)
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    [void](Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $GammaEntry `
        -ClaimApprover {
            param($Plan)
            $Claims.Current = $Plan.Kind -ceq 'ClaimCurrent'
            return $Claims.Current
        })
    Assert-ProjDataRootTest `
        -Condition $Claims.Current `
        -Message 'same-name entry with another File ID bypassed claim'

    $EpsilonEntry = Join-Path $ProjectRoot 'epsilon.cmd'
    [IO.File]::WriteAllText($EpsilonEntry, '@echo original')
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    $EpsilonRoot = Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $EpsilonEntry
    $EpsilonOriginalRecord = (
        Read-ProjEntryIdentityRecord -DataRoot $EpsilonRoot
    ).Value

    $FirstReplacement = Join-Path $ProjectRoot 'epsilon.first.cmd'
    $FirstBackup = Join-Path $ProjectRoot 'epsilon.first.backup.cmd'
    [IO.File]::WriteAllText($FirstReplacement, '@echo first replacement')
    [IO.File]::Replace(
        $FirstReplacement,
        $EpsilonEntry,
        $FirstBackup,
        $true
    )
    [IO.File]::Delete($FirstBackup)
    $RejectedChangedEntry = $false
    try {
        [void](Resolve-ProjProjectDataRoot `
            -ProjHome $ProjHome `
            -ProjectRoot $ProjectRoot `
            -ActionRoot $ActionRoot `
            -EntryFile $EpsilonEntry `
            -ClaimApprover {
                param($Claim)
                $SecondReplacement = Join-Path `
                    $ProjectRoot `
                    'epsilon.second.cmd'
                $SecondBackup = Join-Path `
                    $ProjectRoot `
                    'epsilon.second.backup.cmd'
                [IO.File]::WriteAllText(
                    $SecondReplacement,
                    '@echo second replacement'
                )
                [IO.File]::Replace(
                    $SecondReplacement,
                    $EpsilonEntry,
                    $SecondBackup,
                    $true
                )
                [IO.File]::Delete($SecondBackup)
                return $Claim.Kind -ceq 'ClaimCurrent'
            })
    } catch {
        $RejectedChangedEntry = $_.Exception.Message -like (
            '*state changed during claim*'
        )
    }
    $EpsilonCurrentIdentity = Get-ProjEntryFileIdentity `
        -EntryFile $EpsilonEntry
    $EpsilonPublishedRecord = (
        Read-ProjEntryIdentityRecord -DataRoot $EpsilonRoot
    ).Value
    Assert-ProjDataRootTest `
        -Condition ($RejectedChangedEntry -and
            (Test-ProjEntryIdentityEqual `
                -Record $EpsilonPublishedRecord `
                -Identity $EpsilonCurrentIdentity) -eq $false -and
            [string]$EpsilonPublishedRecord.fileId -ceq
                [string]$EpsilonOriginalRecord.fileId) `
        -Message 'claim approval was applied after the entry File ID changed'

    $DeltaEntry = Join-Path $ProjectRoot 'delta.cmd'
    [IO.File]::WriteAllText($DeltaEntry, '@echo off')
    $DeltaRoot = Join-Path $ProjHome 'data\proj.delta'
    [void][IO.Directory]::CreateDirectory($DeltaRoot)
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    [void](Resolve-ProjProjectDataRoot `
        -ProjHome $ProjHome `
        -ProjectRoot $ProjectRoot `
        -ActionRoot $ActionRoot `
        -EntryFile $DeltaEntry `
        -ClaimApprover {
            param($Plan)
            $Claims.MissingRecord =
                $Plan.Kind -ceq 'ClaimCurrent'
            return $Claims.MissingRecord
        })
    Assert-ProjDataRootTest `
        -Condition $Claims.MissingRecord `
        -Message 'an unrecorded same-name DataRoot bypassed claim'

    $env:SWAWKIT_PROJ_DATA_ROOT = $BetaRoot
    $RejectedForeignRoot = $false
    try {
        [void](Get-ProjDataRootPlan `
            -DataDirectory $DataDirectory `
            -EntryFile $GammaEntry `
            -InheritedDataRoot $BetaRoot)
    } catch {
        $RejectedForeignRoot =
            $_.Exception.Message -like "*Another project's DataRoot*"
    }
    Assert-ProjDataRootTest `
        -Condition $RejectedForeignRoot `
        -Message 'another entry DataRoot was accepted as inherited context'

    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $null,
        [EnvironmentVariableTarget]::Process
    )
    $DuplicateRoot = Join-Path $ProjHome 'data\proj.duplicate'
    [void][IO.Directory]::CreateDirectory($DuplicateRoot)
    [IO.File]::Copy(
        (Join-Path $GammaRoot '_entry.json'),
        (Join-Path $DuplicateRoot '_entry.json'),
        $true
    )
    $RejectedDuplicateIdentity = $false
    try {
        [void](Get-ProjDataRootPlan `
            -DataDirectory $DataDirectory `
            -EntryFile $GammaEntry)
    } catch {
        $RejectedDuplicateIdentity =
            $_.Exception.Message -like '*Multiple project DataRoots*'
    }
    Assert-ProjDataRootTest `
        -Condition $RejectedDuplicateIdentity `
        -Message 'multiple DataRoots with one File ID were not rejected'
} finally {
    [Environment]::SetEnvironmentVariable(
        'SWAWKIT_PROJ_DATA_ROOT',
        $PreviousDataRoot,
        [EnvironmentVariableTarget]::Process
    )
    if ([IO.Directory]::Exists($TemporaryRoot)) {
        [IO.Directory]::Delete($TemporaryRoot, $true)
    }
}

Write-Host '[PASS] Proj entry identity and DataRoot claims' `
    -ForegroundColor Green
$global:LASTEXITCODE = 0
