Set-StrictMode -Version 2.0

$script:XvenvGenerationPlaceholder = '__XVENV_GENERATION_ID__'

function ConvertTo-XvenvPowerShellLiteral {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace("'", "''")
}

function ConvertTo-XvenvBatchValue {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace('%', '%%')
}

function ConvertTo-XvenvEnvironmentScripts {
    param([Parameter(Mandatory = $true)][object]$Plan)

    $Cmd = [Text.StringBuilder]::new()
    [void]$Cmd.AppendLine('@echo off')
    [void]$Cmd.AppendLine('rem Generated by xvenv. Re-run "xvenv set ..." instead of editing.')
    [void]$Cmd.AppendLine("set `"XVENV_GENERATION_ID=$script:XvenvGenerationPlaceholder`"")

    $Ps1 = [Text.StringBuilder]::new()
    [void]$Ps1.AppendLine('# Generated by xvenv. Re-run "xvenv set ..." instead of editing.')
    [void]$Ps1.AppendLine("`$env:XVENV_GENERATION_ID = '$script:XvenvGenerationPlaceholder'")

    foreach ($Name in $Plan.variables.Keys) {
        $Value = $Plan.variables[$Name]
        if ($null -eq $Value) {
            [void]$Cmd.AppendLine("set `"$Name=`"")
            [void]$Ps1.AppendLine("Remove-Item -LiteralPath 'Env:$Name' -ErrorAction SilentlyContinue")
            continue
        }
        $CmdValue = ConvertTo-XvenvBatchValue ([string]$Value)
        $PsValue = ConvertTo-XvenvPowerShellLiteral ([string]$Value)
        [void]$Cmd.AppendLine("set `"$Name=$CmdValue`"")
        [void]$Ps1.AppendLine("`$env:$Name = '$PsValue'")
    }

    $PathPrefix = [string]::Join(
        [IO.Path]::PathSeparator,
        [string[]]$Plan.pathPrefixes.ToArray()
    )
    if (-not [string]::IsNullOrWhiteSpace($PathPrefix)) {
        $CmdPrefix = ConvertTo-XvenvBatchValue $PathPrefix
        $PsPrefix = ConvertTo-XvenvPowerShellLiteral "$PathPrefix$([IO.Path]::PathSeparator)"
        [void]$Cmd.AppendLine("set `"PATH=$CmdPrefix;%PATH%`"")
        [void]$Ps1.AppendLine("`$env:PATH = '$PsPrefix' + `$env:PATH")
    }

    $UnversionedCmd = $Cmd.ToString()
    $UnversionedPs1 = $Ps1.ToString()
    $GenerationId = (Get-XvenvSha256 "$UnversionedCmd`n---`n$UnversionedPs1").Substring(0, 16)
    return [pscustomobject]@{
        GenerationId = $GenerationId
        Cmd = $UnversionedCmd.Replace($script:XvenvGenerationPlaceholder, $GenerationId)
        Ps1 = $UnversionedPs1.Replace($script:XvenvGenerationPlaceholder, $GenerationId)
    }
}

function Publish-XvenvEnvironmentScripts {
    param(
        [Parameter(Mandatory = $true)][object]$Context,
        [Parameter(Mandatory = $true)][object]$Scripts
    )

    $CmdEncoding = [Text.UTF8Encoding]::new($false)
    $Ps1Encoding = [Text.UTF8Encoding]::new($true)
    $CurrentCmd = if ([IO.File]::Exists($Context.EnvCmdPath)) {
        [IO.File]::ReadAllText($Context.EnvCmdPath, $CmdEncoding)
    } else {
        $null
    }
    $CurrentPs1 = if ([IO.File]::Exists($Context.EnvPs1Path)) {
        [IO.File]::ReadAllText($Context.EnvPs1Path, $Ps1Encoding)
    } else {
        $null
    }
    if ($CurrentCmd -ceq [string]$Scripts.Cmd -and
        $CurrentPs1 -ceq [string]$Scripts.Ps1) {
        return $false
    }

    # env.ps1 is published last because status and shell use it as the primary artifact.
    Write-XvenvTextAtomic `
        -Path $Context.EnvCmdPath `
        -Content ([string]$Scripts.Cmd) `
        -Encoding $CmdEncoding
    Write-XvenvTextAtomic `
        -Path $Context.EnvPs1Path `
        -Content ([string]$Scripts.Ps1) `
        -Encoding $Ps1Encoding
    return $true
}

function ConvertFrom-XvenvEntryList {
    param(
        [AllowNull()][string]$Value,
        [Parameter(Mandatory = $true)][object]$Catalog,
        [switch]$Component
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return [object[]]@()
    }
    $Collection = if ($Component) { $Catalog.Components } else { $Catalog.Tools }
    $Entries = [Collections.Generic.List[object]]::new()
    $Seen = @{}
    foreach ($Encoded in $Value.Split(';')) {
        $Parts = [string[]]$Encoded.Split('|')
        if ($Parts.Count -ne 3) {
            throw "Invalid generated xvenv entry: $Encoded"
        }
        $Name = $Parts[0].ToLowerInvariant()
        $Version = Get-XvenvSafeSegment -Value $Parts[1] -Description "version for $Name"
        $Sha256 = $Parts[2].ToLowerInvariant()
        if (-not $Collection.ContainsKey($Name) -or $Seen.ContainsKey($Name)) {
            throw "Invalid generated xvenv module: $Name"
        }
        if (-not [string]::IsNullOrWhiteSpace($Sha256) -and
            $Sha256 -notmatch '^[a-f0-9]{64}$') {
            throw "Invalid generated SHA-256 for $Name $Version."
        }
        $NeedsDigest = Test-XvenvDefinitionHasArtifact $Collection[$Name]
        if ($NeedsDigest -and [string]::IsNullOrWhiteSpace($Sha256)) {
            throw "The generated xvenv entry for $Name $Version is missing its SHA-256."
        }
        if (-not $NeedsDigest -and -not [string]::IsNullOrWhiteSpace($Sha256)) {
            throw "The generated xvenv entry for $Name $Version has an unexpected SHA-256."
        }
        $Entry = [ordered]@{ name = $Name; version = $Version }
        if (-not [string]::IsNullOrWhiteSpace($Sha256)) {
            $Entry.sha256 = $Sha256
        }
        [void]$Entries.Add($Entry)
        $Seen[$Name] = $true
    }
    return $Entries.ToArray()
}

function Import-XvenvGeneratedEnvironment {
    param([Parameter(Mandatory = $true)][object]$Context)

    $HasCmd = [IO.File]::Exists($Context.EnvCmdPath)
    $HasPs1 = [IO.File]::Exists($Context.EnvPs1Path)
    if (-not $HasCmd -and -not $HasPs1) {
        throw "xvenv is not configured for this project. Run: $(Get-XvenvSetCommandExample $Context.Catalog)"
    }
    if (-not $HasCmd -or -not $HasPs1) {
        throw 'The generated xvenv environment is incomplete. Run xvenv set again.'
    }

    $CmdContent = [IO.File]::ReadAllText($Context.EnvCmdPath)
    $Match = [regex]::Match(
        $CmdContent,
        '(?im)^set "XVENV_GENERATION_ID=([a-f0-9]{16})"\s*$'
    )
    if (-not $Match.Success) {
        throw 'The generated xvenv environment is incomplete. Run xvenv set again.'
    }

    Remove-Item Env:XVENV_GENERATION_ID -ErrorAction SilentlyContinue
    . $Context.EnvPs1Path
    if ([string]$env:XVENV_GENERATION_ID -ne $Match.Groups[1].Value) {
        throw 'The generated xvenv environment files do not match. Run xvenv set again.'
    }
    $RecordedRoot = Get-XvenvCanonicalPath ([string]$env:XVENV_PROJECT_ROOT)
    if (-not $RecordedRoot.Equals(
        $Context.CanonicalProjectRoot,
        [StringComparison]::OrdinalIgnoreCase
    )) {
        throw "The generated xvenv environment belongs to another project: $($env:XVENV_PROJECT_ROOT)"
    }

    return [pscustomobject]@{
        schema = 'xvenv.plan.v1'
        projectRoot = [string]$env:XVENV_PROJECT_ROOT
        tools = @(ConvertFrom-XvenvEntryList `
            -Value ([string]$env:XVENV_TOOLS) `
            -Catalog $Context.Catalog)
        components = @(ConvertFrom-XvenvEntryList `
            -Value ([string]$env:XVENV_COMPONENTS) `
            -Catalog $Context.Catalog `
            -Component)
    }
}
