Set-StrictMode -Version 2.0

$script:XvenvLinkMarker = 'rem Generated by xvenv link. Re-run "xvenv link" instead of editing.'

function Get-XvenvLinkPath {
    param([Parameter(Mandatory = $true)][object]$Context)

    return Join-Path $Context.ProjectRoot 'xvenv.link.cmd'
}

function ConvertTo-XvenvLinkScript {
    param([Parameter(Mandatory = $true)][object]$Context)

    $EntryPath = Get-XvenvFullPath (Join-Path $Context.ToolboxRoot 'xvenv.ps1')
    $BatchEntryPath = ConvertTo-XvenvBatchValue $EntryPath
    $BatchProjectRoot = ConvertTo-XvenvBatchValue $Context.ProjectRoot

    $Content = @"
@echo off
setlocal DisableDelayedExpansion
$script:XvenvLinkMarker

set "XVENV_LINK_ENTRY=$BatchEntryPath"
set "XVENV_LINK_POWERSHELL=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"
if not exist "%XVENV_LINK_ENTRY%" (
    >&2 echo [ERROR] The linked xvenv toolbox is no longer available.
    >&2 echo [ERROR] Run "xvenv link" again from this project.
    exit /b 1
)
if not exist "%XVENV_LINK_POWERSHELL%" (
    >&2 echo [ERROR] Windows PowerShell is required: "%XVENV_LINK_POWERSHELL%"
    exit /b 1
)

set "XVENV_LINK_PROJECT_ROOT=$BatchProjectRoot"
"%XVENV_LINK_POWERSHELL%" -NoLogo -NoProfile -ExecutionPolicy Bypass -Command "`$ErrorActionPreference = 'Stop'; Set-Location -LiteralPath `$env:XVENV_LINK_PROJECT_ROOT; & `$env:XVENV_LINK_ENTRY --xvenv-follow-link; exit `$LASTEXITCODE"
set "XVENV_LINK_EXIT_CODE=%ERRORLEVEL%"
exit /b %XVENV_LINK_EXIT_CODE%
"@
    return $Content.
        Replace("`r`n", "`n").
        Replace("`r", "`n").
        Replace("`n", "`r`n")
}

function Publish-XvenvLinkScript {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $Encoding = [Text.UTF8Encoding]::new($false)
    if ([IO.File]::Exists($Path)) {
        $Current = [IO.File]::ReadAllText($Path, $Encoding)
        if ($Current -ceq $Content) {
            return $false
        }
        $Normalized = $Current.
            Replace("`r`n", "`n").
            Replace("`r", "`n")
        $ExpectedHeader = [string]::Join("`n", @(
            '@echo off',
            'setlocal DisableDelayedExpansion',
            $script:XvenvLinkMarker
        ))
        if (-not $Normalized.StartsWith(
            $ExpectedHeader,
            [StringComparison]::Ordinal
        )) {
            throw "Refusing to overwrite a file not generated by xvenv: $Path"
        }
    }

    Write-XvenvTextAtomic -Path $Path -Content $Content -Encoding $Encoding
    return $true
}

function Invoke-XvenvLink {
    param([Parameter(Mandatory = $true)][object]$Context)

    Assert-XvenvNotActive
    $Plan = Import-XvenvGeneratedEnvironment -Context $Context
    Assert-XvenvPlanInstalled -Context $Context -Plan $Plan

    $EntryPath = Get-XvenvFullPath (Join-Path $Context.ToolboxRoot 'xvenv.ps1')
    if (-not [IO.File]::Exists($EntryPath)) {
        throw "The xvenv PowerShell entry is missing: $EntryPath"
    }

    $Path = Get-XvenvLinkPath -Context $Context
    $Content = ConvertTo-XvenvLinkScript -Context $Context
    $Changed = Publish-XvenvLinkScript -Path $Path -Content $Content
    if ($Changed) {
        Write-Host "xvenv link created: $Path" -ForegroundColor Green
    } else {
        Write-Host 'xvenv link is already up to date.' -ForegroundColor Green
    }
    return 0
}

function Invoke-XvenvFollowLink {
    param([Parameter(Mandatory = $true)][object]$Context)

    $ProjectRoot = [string]$env:XVENV_LINK_PROJECT_ROOT
    if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
        throw 'The xvenv link is invalid. Run xvenv link again.'
    }
    foreach ($Name in @(
        'XVENV_LINK_ENTRY',
        'XVENV_LINK_POWERSHELL',
        'XVENV_LINK_PROJECT_ROOT'
    )) {
        Remove-Item -LiteralPath "Env:$Name" -ErrorAction SilentlyContinue
    }
    $LinkedContext = New-XvenvContext `
        -WorkingDirectory $Context.InvocationDirectory `
        -ProjectRoot $ProjectRoot `
        -ToolboxRoot $Context.ToolboxRoot `
        -DataRoot $Context.DataRoot `
        -Catalog $Context.Catalog `
        -RunExternal $Context.RunExternal `
        -LaunchTerminal $Context.LaunchTerminal
    return Invoke-XvenvOpenTerminal -Context $LinkedContext
}
